/* V2.4.1 FIX */
(()=>{"use strict";const $=i=>document.getElementById(i),N=(i,f=0)=>Number($(i)?.value)||f,C=(v,a,b)=>Math.max(a,Math.min(b,v)),S={t0:performance.now(),last:performance.now(),sample:0,h:[],ev:[],fr:0,db:0,ne:0,bol:0,at:0,atu:0,et:null,b:null};
const T=(i,v)=>{let e=$(i);if(e)e.textContent=v},P=(i,v)=>{let e=$(i);if(e)e.value=v},log=s=>{S.ev.push({t:(performance.now()-S.t0)/1000,s});T("v24s",s)};
function panel(){let a=document.querySelector("aside.controls");if(!a||$("therapyV24"))return;let c=document.createElement("section");c.className="card";c.id="therapyV24";c.innerHTML=`<h2>Terapie dinamiche</h2><div class="therapy-grid"><div class="therapy"><b>Fluid challenge</b><small>2 mL/kg in 30 s</small><button id="b24">Somministra</button></div><div class="therapy"><b>Cristalloidi</b><label>mL/kg/h <input id="fr24" type="number" value="2"></label><button id="frb24">Avvia</button></div><div class="therapy"><b>Dobutamina</b><label>µg/kg/min <input id="db24" type="number" step=".5" value="5"></label><button id="dbb24">Avvia</button></div><div class="therapy"><b>Noradrenalina</b><label>µg/kg/min <input id="ne24" type="number" step=".01" value=".10"></label><button id="neb24">Avvia</button></div><div class="therapy"><b>Atropina</b><label>µg/kg <input id="at24" type="number" value="20"></label><button id="atb24">Somministra</button></div></div><div id="v24s" class="status">Pronto.</div>`;a.appendChild(c);
function tog(b,i,k,n){$(b).onclick=()=>{if(S[k]){S[k]=0;$(b).classList.remove("active-therapy");$(b).textContent="Avvia";log(n+" OFF")}else{S[k]=Math.max(0,N(i));$(b).classList.add("active-therapy");$(b).textContent="ATTIVA — Stop";log(n+" ON")}};$(i).oninput=()=>{if(S[k])S[k]=Math.max(0,N(i))}}
tog("frb24","fr24","fr","Cristalloidi");tog("dbb24","db24","db","Dobutamina");tog("neb24","ne24","ne","Noradrenalina");
$("b24").onclick=()=>{S.bol=1;$("b24").classList.add("pulse-therapy");log("Fluid challenge");setTimeout(()=>{S.bol=0;$("b24")?.classList.remove("pulse-therapy")},30000)};
$("atb24").onclick=()=>{S.at=C(N("at24",20)/20,.25,3);S.atu=performance.now()+180000;$("atb24").classList.add("pulse-therapy");log("Atropina");setTimeout(()=>$("atb24")?.classList.remove("pulse-therapy"),4000)}}
const M=[["HR","FC"],["SpO2","SpO₂"],["EtCO2","EtCO₂"],["RR","FR"],["SAP","SAP"],["DAP","DAP"],["MAP","MAP"],["CO","CO"],["CI","CI"],["SV","SV"],["SVI","SVI"],["SVR","SVR"],["SVRI","SVRI"],["PPV","PPV"],["SVV","SVV"],["dPdt","dP/dtmax"],["CCE","CCE"],["Ea","Ea"],["CPO","CPO"],["Temp","Temperatura"],["Preload","Precarico"],["Afterload","Afterload"],["Contractility","Contrattilità"]];
function trend(){let m=document.querySelector("section.monitor");if(!m||$("trendV24"))return;let c=document.createElement("section");c.className="card trend-card";c.id="trendV24";c.innerHTML=`<div class="trend-head"><h2>Trend monitor</h2><b id="clk24">00:00</b></div><div class="trend-controls"><select id="met24"></select><select id="win24"><option value="120">2 min</option><option value="300">5 min</option><option value="600">10 min</option><option value="1800">30 min</option></select></div><canvas id="tr24"></canvas><div id="leg24" class="trend-legend"></div><div id="ev24" class="trend-events"></div>`;m.appendChild(c);M.forEach(x=>{let o=document.createElement("option");o.value=x[0];o.textContent=x[1];$("met24").appendChild(o)});$("met24").value="MAP";$("met24").onchange=draw;$("win24").onchange=draw}
function draw(){let c=$("tr24");if(!c)return,r=c.getBoundingClientRect(),d=devicePixelRatio||1,w=r.width,h=Math.max(150,r.height);c.width=w*d;c.height=h*d;let g=c.getContext("2d");g.setTransform(d,0,0,d,0,0);g.clearRect(0,0,w,h);let k=$("met24").value,win=+($("win24").value),now=(performance.now()-S.t0)/1000,H=S.h.filter(p=>p.t>=now-win),v=H.map(p=>p[k]).filter(Number.isFinite);if(!v.length)return;let lo=Math.min(...v),hi=Math.max(...v);if(lo===hi){lo-=1;hi+=1}g.strokeStyle="#39ef8b";g.lineWidth=2;g.beginPath();H.forEach((p,i)=>{let x=w*(1-(now-p.t)/win),y=h-(p[k]-lo)/(hi-lo)*h;i?g.lineTo(x,y):g.moveTo(x,y)});g.stroke();T("leg24",`${k}: ${v.at(-1).toFixed(2)} · min ${Math.min(...v).toFixed(2)} · max ${Math.max(...v).toFixed(2)}`);T("ev24",S.ev.slice(-4).map(e=>`${Math.floor(e.t/60)}:${String(Math.floor(e.t%60)).padStart(2,"0")} ${e.s}`).join(" • "))}
function init(){if(S.b)return;S.b={hr:N("hr",90),pre:N("preload",100),con:N("contractility",100),tone:N("vascularTone",100),rr:N("rr",18)};S.et=N("etco2",38);$("etco2")?.addEventListener("change",()=>S.et=N("etco2",38))}
function calc(dt){init();let b=S.b;if(S.fr)b.pre=C(b.pre+S.fr*dt/3600*.9,20,180);if(performance.now()>S.atu)S.at=0;let pre=C(b.pre+(S.bol?22:0),20,180),con=C(b.con+S.db*4+S.ne*3,20,190),tone=C(b.tone+S.ne*80-S.db*1.2,30,220),hr=C(b.hr+S.at*25+S.db*.6+S.ne*1.5,0,260),rr=Math.max(0,N("rr",b.rr)),sv=C(36*Math.pow(pre/100,.72)*Math.pow(con/100,.7),3,75),co=C(sv*hr/1000,.05,8),svr=C(1800*tone/100,400,3600),map=C(co*svr/80,15,170),pp=C(sv/36*50,10,90),dap=C(map-pp/3,8,140),sap=C(dap+pp,18,230),ppv=C(8+Math.max(0,100-pre)*.23,2,35),svv=C(ppv*1.08,2,38),dpdt=C(950*con/100*(sap/118),150,2400),ea=C(sap*.9/Math.max(sv,3),.3,10),cce=C(.35*con/100*(co/3.2)/Math.pow(tone/100,.35),.02,.9),cpo=C(map*co/451,.01,2.5),vent=rr?C(rr/b.rr,.35,2.5):.2,et=C(S.et*Math.pow(C(co/3.2,.05,2.2),.38)/Math.pow(vent,.7),3,75);return{pre,con,tone,hr,rr,sv,co,svr,map,sap,dap,ppv,svv,dpdt,ea,cce,cpo,et}}
function apply(x){P("hr",Math.round(x.hr));P("preload",Math.round(x.pre));P("contractility",Math.round(x.con));P("vascularTone",Math.round(x.tone));let bsa=Math.max(.25,.101*Math.pow(N("weight",25),2/3)),o={sap:Math.round(x.sap),dap:Math.round(x.dap),co:x.co.toFixed(2),ci:(x.co/bsa).toFixed(2),sv:Math.round(x.sv),svi:(x.sv/bsa).toFixed(1),svr:Math.round(x.svr),svri:Math.round(x.svr*bsa),ppv:Math.round(x.ppv),svv:Math.round(x.svv),dpdt:Math.round(x.dpdt),cce:x.cce.toFixed(2),ea:x.ea.toFixed(2),cpo:x.cpo.toFixed(2)};Object.entries(o).forEach(([k,v])=>P(k,v));if(typeof render==="function")render();T("vet",Math.round(x.et));T("vart",`${Math.round(x.sap)}/${Math.round(x.dap)}`);T("vmap",Math.round(x.map))}
function loop(now){let dt=Math.min(.25,(now-S.last)/1000);S.last=now,x=calc(dt);apply(x);let t=(now-S.t0)/1000;T("clk24",`${String(Math.floor(t/60)).padStart(2,"0")}:${String(Math.floor(t%60)).padStart(2,"0")}`);if(now-S.sample>1000){S.sample=now;let bsa=Math.max(.25,.101*Math.pow(N("weight",25),2/3));S.h.push({t,HR:x.hr,SpO2:N("spo2",98),EtCO2:x.et,RR:x.rr,SAP:x.sap,DAP:x.dap,MAP:x.map,CO:x.co,CI:x.co/bsa,SV:x.sv,SVI:x.sv/bsa,SVR:x.svr,SVRI:x.svr*bsa,PPV:x.ppv,SVV:x.svv,dPdt:x.dpdt,CCE:x.cce,Ea:x.ea,CPO:x.cpo,Temp:N("temp",38.3),Preload:x.pre,Afterload:x.tone,Contractility:x.con});if(S.h.length>3600)S.h.shift();draw()}requestAnimationFrame(loop)}
function boot(){panel();trend();init();log("V2.4.1 attiva");requestAnimationFrame(loop)}document.readyState==="loading"?document.addEventListener("DOMContentLoaded",boot,{once:true}):boot()})();