/* V2.4 Dynamic Trends — integrated physiology */
(()=>{const $=i=>document.getElementById(i),C=(v,a,b)=>Math.max(a,Math.min(b,v)),n=(i,f=0)=>+($(i)?.value??f),S={ne:0,db:0,fr:0,bol:0,at:0,t0:performance.now(),last:performance.now(),baseEt:null,base:null,events:[],hist:[]};
const set=(id,v)=>{let e=$(id);if(e){e.value=v;e.dispatchEvent(new Event("input",{bubbles:true}));e.dispatchEvent(new Event("change",{bubbles:true}))}},txt=(id,v)=>{let e=$(id);if(e)e.textContent=v};
function event(s){S.events.push({t:(performance.now()-S.t0)/1000,s});txt("v24Status",s)}
function toggle(btn,input,key,name){$(btn).onclick=()=>{if(S[key]){S[key]=0;btn.classList.remove("active-therapy");btn.textContent="Avvia";event(name+" interrotta")}else{S[key]=n(input);btn.classList.add("active-therapy");btn.textContent="ATTIVA — Stop";event(name+" avviata")}};$(input).addEventListener("input",()=>{if(S[key])S[key]=n(input)})}
function panel(){if($("therapyV24"))return;let a=document.querySelector("aside");if(!a)return;let c=document.createElement("section");c.className="card";c.id="therapyV24";c.innerHTML=`<h2>Interventi terapeutici</h2><div class="therapy-grid">
<div class="therapy"><b>Fluid challenge</b><small>2 mL/kg in 30 sec</small><button id="bol">Somministra</button></div>
<div class="therapy"><b>Cristalloidi</b><label>mL/kg/h <input id="fr" type="number" min="0" max="50" step="1" value="0"></label><button id="frb">Avvia</button></div>
<div class="therapy"><b>Dobutamina</b><label>µg/kg/min <input id="db" type="number" min="0" max="20" step=".5" value="5"></label><button id="dbb">Avvia</button></div>
<div class="therapy"><b>Noradrenalina</b><label>µg/kg/min <input id="ne" type="number" min="0" max="2" step=".01" value=".1"></label><button id="neb">Avvia</button></div>
<div class="therapy"><b>Atropina</b><label>µg/kg <input id="at" type="number" min="0" max="100" step="1" value="20"></label><button id="atb">Somministra</button></div></div><div id="v24Status" class="status">Nessuna terapia attiva.</div>`;a.appendChild(c);
toggle($("frb"),"fr","fr","Cristalloidi");toggle($("dbb"),"db","db","Dobutamina");toggle($("neb"),"ne","ne","Noradrenalina");
$("bol").onclick=()=>{S.bol=1;$("bol").classList.add("pulse-therapy");event("Fluid challenge 2 mL/kg");setTimeout(()=>{S.bol=0;$("bol").classList.remove("pulse-therapy")},30000)};
$("atb").onclick=()=>{S.at=C(n("at",20)/20,.25,3);$("atb").classList.add("pulse-therapy");event("Atropina "+n("at",20)+" µg/kg");setTimeout(()=>{$("atb").classList.remove("pulse-therapy")},5000);setTimeout(()=>S.at=0,180000)}}
function trend(){let m=document.querySelector(".monitor");if(!m||$("trendV24"))return;let c=document.createElement("section");c.className="card trend-card";c.id="trendV24";c.innerHTML=`<div class="trend-head"><h2>Trend monitor — tutti i parametri</h2><b id="caseClock">00:00</b></div>
<div class="trend-controls"><select id="trendPreset"><option>Emodinamica</option><option>Pressione</option><option>Perfusione</option><option>Respiratorio</option><option>Tutti</option></select><select id="trendMetric"></select></div>
<canvas id="trendCanvas"></canvas><div id="trendLegend" class="trend-legend"></div><div id="trendEvents" class="trend-events"></div>`;m.appendChild(c);
const metrics=["HR","SpO2","EtCO2","RR","SAP","DAP","MAP","CO","CI","SV","SVI","SVR","SVRI","PPV","SVV","dPdt","CCE","Ea","CPO","Temp","Preload","Afterload","Contractility"];
const sm=$("trendMetric");metrics.forEach(x=>{let o=document.createElement("option");o.value=x;o.textContent=x;sm.appendChild(o)});sm.value="MAP";
$("trendPreset").addEventListener("change",()=>{const p=$("trendPreset").value,def={Emodinamica:"CO",Pressione:"MAP",Perfusione:"SV",Respiratorio:"EtCO2",Tutti:"MAP"};sm.value=def[p]||"MAP";drawTrend()});sm.addEventListener("change",drawTrend)}
function drawTrend(){let c=$("trendCanvas");if(!c)return;let r=c.getBoundingClientRect(),d=devicePixelRatio||1;c.width=r.width*d;c.height=r.height*d;let g=c.getContext("2d");g.setTransform(d,0,0,d,0,0),w=r.width,h=r.height;g.clearRect(0,0,w,h);g.strokeStyle="rgba(120,150,160,.16)";g.lineWidth=1;for(let y=15;y<h;y+=30){g.beginPath();g.moveTo(0,y);g.lineTo(w,y);g.stroke()}
let key=$("trendMetric")?.value||"MAP",H=S.hist.slice(-600),vals=H.map(p=>p[key]).filter(Number.isFinite);if(!vals.length)return;let lo=Math.min(...vals),hi=Math.max(...vals);if(hi===lo){lo-=1;hi+=1}else{let pad=(hi-lo)*.12;lo-=pad;hi+=pad}
g.strokeStyle="#39ef8b";g.lineWidth=2;g.beginPath();H.forEach((p,i)=>{let v=p[key];if(!Number.isFinite(v))return;let x=H.length<2?0:i/(H.length-1)*w,y=h-((v-lo)/(hi-lo))*h;i?g.lineTo(x,y):g.moveTo(x,y)});g.stroke();txt("trendLegend",key+"  "+(vals.at(-1)?.toFixed?.(2)??vals.at(-1))+"   min "+lo.toFixed(1)+" · max "+hi.toFixed(1));let ev=S.events.slice(-5).map(e=>Math.floor(e.t/60)+":"+String(Math.floor(e.t%60)).padStart(2,"0")+" "+e.s).join("  •  ");txt("trendEvents",ev)}
function base(){if(!S.base){S.base={hr:n("hr",90),pre:n("preload",100),con:n("contractility",100),tone:n("vascularTone",100),rr:n("rr",18)};S.baseEt=n("etco2",38)}}
function loop(){base();let now=performance.now(),dt=Math.min(.2,(now-S.last)/1000);S.last=now;let b=S.base;if(S.fr)b.pre=C(b.pre+S.fr*dt/3600*.8,35,170);
let hr=b.hr+(S.at?C(25*S.at,8,65):0)+S.db*.7+S.ne*2,pre=C(b.pre+S.bol*22,30,180),con=C(b.con+S.db*4.2+S.ne*4,25,190),tone=C(b.tone+S.ne*75-S.db*1.5,25,220),fill=C(pre/100,.25,1.7),ino=C(con/100,.25,1.9),aft=C(tone/100,.3,2.2),sv=36*Math.pow(fill,.72)*Math.pow(ino,.60)/Math.pow(aft,.34),co=sv*hr/1000,map=C(18+co*(15.5*aft),25,190),sys=C(map+(18+12*ino)*C(sv/36,.55,1.8),35,240),dia=C(map-(11+7/aft),18,160),ppv=C(7+Math.max(0,1-fill)*28-S.bol*5,2,35);
let rr=Math.max(1,n("rr",b.rr)),vent=C(rr/b.rr,.45,2.2),et=C(S.baseEt*Math.pow(C(co/3.24,.12,2),.42)/Math.pow(vent,.72),8,70);
set("hr",Math.round(hr));set("preload",Math.round(pre));set("contractility",Math.round(con));set("vascularTone",Math.round(tone));set("co",co.toFixed(2));set("ppv",Math.round(ppv));
txt("vhr",Math.round(hr));txt("vet",Math.round(et));txt("vco",co.toFixed(2));txt("vppv",Math.round(ppv));txt("vart",Math.round(sys)+"/"+Math.round(dia));txt("vmap",Math.round(map));
let t=(now-S.t0)/1000,mm=Math.floor(t/60),ss=Math.floor(t%60);txt("caseClock",String(mm).padStart(2,"0")+":"+String(ss).padStart(2,"0"));
if(!S.lr||now-S.lr>1000){S.lr=now;let ci=co/0.864,svi=sv/0.864,svr=map*80/Math.max(.1,co),svri=svr*.864,svv=Math.max(2,ppv+1),dpdt=850*ino*(.75+.25*aft),cce=.35*ino/Math.pow(aft,.42),ea=map/Math.max(12,sv),cpo=map*co/451;
S.hist.push({t,HR:hr,SpO2:n("spo2",98),EtCO2:et,RR:rr,SAP:sys,DAP:dia,MAP:map,CO:co,CI:ci,SV:sv,SVI:svi,SVR:svr,SVRI:svri,PPV:ppv,SVV:svv,dPdt:dpdt,CCE:cce,Ea:ea,CPO:cpo,Temp:n("temp",38.3),Preload:pre,Afterload:tone,Contractility:con});if(S.hist.length>1800)S.hist.shift();drawTrend()}requestAnimationFrame(loop)}
function etManual(){let e=$("etco2");if(!e)return;e.addEventListener("input",()=>{let v=+e.value;if(Number.isFinite(v)&&v>0)S.baseEt=v});e.addEventListener("change",()=>{let v=+e.value;if(Number.isFinite(v)&&v>0)S.baseEt=v})}
function boot(){panel();trend();base();etManual();requestAnimationFrame(loop)}document.readyState==="loading"?document.addEventListener("DOMContentLoaded",boot):boot()})();